note_taker/accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = "accounts"

urlpatterns = [
    path("sign-up/", views.sign_up, name='sign_up'),
    path("log-in/", LoginView.as_view(template_name="accounts/log-in.html"), name="log_in"),
    path("log-out/", LogoutView.as_view(), name='log_out'),
]

note_taker/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('accounts/', include('accounts.urls')),
]

note_taker/notes/urls.py
from django.urls import path 

from . import views

app_name = "notes"


urlpatterns = [
    path('notes/', views.notes_list, name='note_list'),
    path('add/note/', views.add_note, name='add_note'),
    path('edit/note/<int:note_id>/', views.update_note, name='update_note'),
    path('note/<int:note_pk>/', views.note_detail, name='note_detail'),
    path('confirm-delete/<int:note_pk>/', views.confirm_delete, name='confirm_delete'),
    path('delete-note/<int:note_id>/', views.delete_note, name='delete_note'),
]

note_taker/notes/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Category(models.TextChoices):
    WORK = "WK", "Work"
    PERSONAL = "PSNL", "Personal"
    IDEAS = "IDEAS", "Ideas"


class Note(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.CharField(choices=Category.choices, max_length=5, default=Category.PERSONAL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notes")

note_taker/notes/forms.py
from django import forms

from .models import Note, Category

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content', 'category']


class SearchForm(forms.Form):
    query = forms.CharField(max_length=255, required=False)
    

class FilterForm(forms.Form):
    category = forms.ChoiceField(choices=Category.choices, initial=Category.WORK, required=False)

note_taker/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def sign_up(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account created successfully")
            return redirect("accounts:log_in")
    return render(request, "accounts/sign-up.html", {'form': form})

note_taker/notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Note
from .forms import NoteForm, SearchForm, FilterForm

# Create your views here.
def notes_list(request):
    notes = Note.objects.all()

    search_form = SearchForm(request.GET)

    if search_form.is_valid():
        query = search_form.cleaned_data.get('query')
        if query:
            notes = Note.objects.all().filter(Q(title__icontains=query) | Q(content__icontains=query))

    filter_form = FilterForm(request.GET)
    if filter_form.is_valid():
        category = filter_form.cleaned_data.get('category')
        if category:
            notes = notes.filter(category=category)
    context = {
        "notes": notes, 
        'search_form': search_form,
        'filter_form': filter_form
    }
    return render(request, "notes/note-list.html", context)


def note_detail(request, note_pk):
    note = get_object_or_404(Note, pk=note_pk)
    return render(request, "notes/note.html", {'note': note})


@login_required
def add_note(request):
    form = NoteForm()
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.added_by = request.user
            note.save()
            return redirect("notes:note_list")
    context = {'form': form}
    return render(request, "notes/add-note.html", context)


@login_required
def update_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.user != note.added_by:
        messages.error(request, "You do not have permission to perform that action")
        return redirect("notes:note_list")
    form = NoteForm(instance=note)
    if request.method == "POST":
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect("notes:note_detail", note_pk=note_id)
    context = {'note': note, 'form': form}
    return render(request, "notes/edit-note.html", context)

@login_required
def confirm_delete(request, note_pk):
    note = get_object_or_404(Note, pk=note_pk)
    if request.user != note.added_by:
        messages.error(request, "You do not have permission to perform that action")
        return redirect("notes:note_list")
    return render(request, "notes/confirm-delete.html", context={"note": note})

@login_required
def delete_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.user != note.added_by:
        messages.error(request, "You do not have permission to perform that action")
        return redirect("notes:note_list")
    if request.method == "POST":
        note.delete()
    return redirect("notes:note_list")

note_taker/templates/notes/add-note.html
{% extends "partials/base.html" %}

{% block title %}
Add Note
{% endblock title %}

{% block body %}

<div>
    <form action="{% url 'notes:add_note' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Note</button>
    </form>
</div>

{% endblock body %}

note_taker/templates/notes/confirm-delete.html
{% extends "partials/base.html" %}

{% block title %}
Confirm Note Deletion
{% endblock title %}

{% block body %}
<div>
    <p>Are you sure you want to delete this note?</p>
        <div>
            <h2>{{ note.title }}</h2>
            <p>{{ note.content }}</p>
            <p>{{ note.get_category_display }}</p>
            <p>{{ note.created_at }}</p>
        </div>
</div>

<div>
    <form action="{% url 'notes:delete_note' note.id %}" method="POST">
        {% csrf_token %}
        <button type="submit">Yes, I am sure</button>
    </form>
    <a href="{% url 'notes:note_detail' note.pk %}">No, take me back</a>
</div>
{% endblock body %}

note_taker/templates/notes/edit-note.html
{% extends "partials/base.html" %}

{% block title %}
Edit Note
{% endblock title %}

{% block body %}

<h2>Edit "{{ note.title }}"</h2>
<form action="{% url 'notes:update_note' note.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit Note</button>
</form>
{% endblock body %}

note_taker/templates/notes/note-list.html
{% extends "partials/base.html" %}

{% block title %}
Note Taker
{% endblock title %}

{% block body %}


<div>
    <a href="{% url 'notes:add_note' %}">Add Note</a>
</div>
<div>
    <form>
        {{ search_form.as_p }}
        <button type="submit">Search</button>
    </form>
</div>
<div>
    {% comment %} <form>
        {{ filter_form.as_p }}
        <button type="submit">Filter</button>
    </form> {% endcomment %}
    {% for key, value in filter_form.fields.category.choices %}
        <a href="{% url 'notes:note_list' %}?category={{ key }}">{{ value }}</a>
    {% endfor %}


</div>
<div>
    {% for note in notes %}
        <div>
            <h2><a href="{% url 'notes:note_detail' note.id %}">{{ note.title }}</a></h2>
        </div>
    {% empty %}
    <p>No notes yet to display</p>
    {% endfor %}
</div>
{% endblock body %}

note_taker/templates/notes/note.html
{% extends "partials/base.html" %}

{% block title %}
{{ note.title }}
{% endblock title %}

{% block body %}


<div>
    <h2>{{ note.title }}</h2>
    <p>{{ note.content }}</p>
    <p>{{ note.get_category_display }}</p>
    <p>{{ note.created_at }}</p>
    <p>Added By: {{ note.added_by }}</p>
</div>
<div>
    {% if note.added_by == request.user %}
        <a href="{% url 'notes:update_note' note.id %}">Edit Note</a>
    {% else %}
        <a class="link-btn disabled"
            aria-disabled="true"
            tabindex="-1"
            title="You don't have permission to edit this note">Edit Note</a>
    {% endif %}
    {% if note.added_by == request.user %}
        <a href="{% url 'notes:confirm_delete' note.id %}">Delete Note</a>
    {% else %}
        <a class="link-btn disabled"
            aria-disabled="true"
            tabindex="-1"
            title="You don't have permission to edit this note">Delete Note</a>
    {% endif %}
</div>
{% endblock body %}