lms/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('authors/', include('authors.urls')), 
    path('dtl/', include('dtl.urls')), 
    path('', include('pages.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lms/dtl/urls.py
from django.urls import path

from . import views

app_name = 'dtl'

urlpatterns = [
    path('demo/', views.django_template_language, name='dtl_demo'),
    path('home/', views.home, name='home'),
    path('models-demo/', views.models_demo, name='models_demo'),
]

lms/library/urls.py
from django.urls import path
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.book_list, name='book_list'),
    path('book/<int:book_id>/', views.book_detail, name='book_detail'),
    path('add/book/', views.create_book, name='create_book'),
    path('add/book/manually-rendered/', views.create_book_manually_rendered, name='create_book_manually_rendered'),
    path('add/book/django-manual-form/', views.create_book_django_manual_form, name='create_book_django_manual_form'),
    path('update/book/model-form/<int:book_pk>/', views.update_book_model_form, name='update_book_model_form'),
    path('update/book/manual-form/<int:pk>/', views.update_book_manual_form, name='update_book_manual_form'),
    path('confirm-delete/<int:pk>/', views.confirm_delete, name='confirm_delete'),
    path('delete-book/<int:book_pk>/', views.delete_book, name='delete_book'),
]

lms/library/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxValueValidator
from django.core.exceptions import ValidationError

from authors.models import Author


def validate_title_has_no_special_chars(value: str):
    if not all(char.isalpha() or char.isspace() for char in value):
        raise ValidationError("Title can only contain alphabets and spaces!")

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255, validators=[MinLengthValidator(10), validate_title_has_no_special_chars])
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    number_of_pages = models.PositiveIntegerField(validators=[MaxValueValidator(7000)])
    published_on = models.DateTimeField()
    cover_image = models.ImageField(upload_to="cover_images/", null=True, blank=True)

    def __str__(self):
        return f"{self.title} by {self.author}"

lms/library/forms.py
from django import forms

from .models import Book
from authors.models import Author


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["title", "author", "number_of_pages", "published_on", "cover_image"]

    # def clean(self):
    #     cleaned_data = super().clean()
    #     title = cleaned_data.get("title")
    #     published_on = cleaned_data.get("published_on")

    #     # Example: forbid books published before 1900
    #     if published_on and published_on.year < 1900:
    #         raise forms.ValidationError("Books published before 1900 are not allowed.")

    #     return cleaned_data


class BookManualForm(forms.Form):
    title = forms.CharField(max_length=255)
    author = forms.ModelChoiceField(queryset=Author.objects.all()) 
    number_of_pages = forms.IntegerField(min_value=1)
    published_on = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    cover_image = forms.ImageField(required=False)

lms/library/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404

from .models import Book
from library.models import Author
from .forms import BookForm, BookManualForm

# Create your views here.

def home(request):
    return render(request, "library/home.html")

def book_list(request):
    return render(request, "library/book-list.html", {"all_books": Book.objects.all()})

# django template language - DTL

def book_detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    # try:
    #     book = Book.objects.get(pk=book_id)
    # except Book.DoesNotExist:
    #     raise Http404("Book does not exist")
    return render(request, "library/book-detail.html", {"book": book})


def create_book(request):
    form = BookForm()
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()       
            return redirect('library:book_list')

    context = {
        'form': form
    }
    return render(request, "library/create-book.html", context)


def create_book_manually_rendered(request):
    all_authors = Author.objects.all()
    form = BookForm()
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()       
            return redirect('library:book_list')
        else:
            print(form.errors)

    context = {
        'form': form,
        'all_authors': all_authors
    }
    return render(request, "library/create-book-manually-rendered.html", context)


def create_book_django_manual_form(request):
    form = BookManualForm()
    if request.method == "POST":
        form = BookManualForm(request.POST, request.FILES)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            # Book.objects.create(
            #     title=cleaned_data.get('title'),
            #     author=cleaned_data.get('author'),
            #     number_of_pages=cleaned_data.get('number_of_pages'),
            #     published_on=cleaned_data.get('published_on'),
            #     cover_image=cleaned_data.get('cover_image')
            # )
            Book.objects.create(**cleaned_data)
            return redirect('library:book_list')


    context = {'form': form}
    return render(request, "library/create-book-django-manual-form.html", context)

def update_book_model_form(request, book_pk):
    book = get_object_or_404(Book, pk=book_pk)
    form = BookForm(instance=book)
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book)

        if form.is_valid():
            form.save()
            return redirect('library:book_list')

    context = {
        'form': form,
        'book': book,
    }
    return render(request, "library/update-book-model-form.html", context)


def update_book_manual_form(request, pk):
    book = get_object_or_404(Book, pk=pk)
    form = BookManualForm(initial={
        'title': book.title,
        'author': book.author,
        'number_of_pages': book.number_of_pages,
        'published_on': book.published_on,
        'cover_image': book.cover_image,
    })
    if request.method == "POST":
        form = BookManualForm(request.POST, request.FILES)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            book.title = cleaned_data.get('title')
            book.author = cleaned_data.get('author')
            book.number_of_pages = cleaned_data.get('number_of_pages')
            book.published_on = cleaned_data.get('published_on')
            book.cover_image = cleaned_data.get('cover_image')
            book.save()
            return redirect('library:book_detail', book_id=pk)
    context = {'form': form, 'book': book}
    return render(request, "library/update-book-django-manual-form.html", context)   


def confirm_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    return render(request, "library/confirm-delete.html", {'book': book})


def delete_book(request, book_pk):
    book = get_object_or_404(Book, pk=book_pk)
    if request.method == "POST":
        book.delete()
    return redirect("library:book_list")

lms/templates/library/book-detail.html
{% extends "partials/base.html" %}

{% block title %}
{{ book.title }}
{% endblock title %}


{% block body %}
<h1>{{ book.title }}</h1>
<div>
    
    <h3>{{ book.title }}</h3>
    <h4>By {{ book.author }}</h4>
    <p>Number of Pages: {{ book.number_of_pages }}</p>
    <p>Published On: {{ book.published_on }}</p>
    {% if book.cover_image %}
        <img width="100" height="100" src="{{ book.cover_image.url }}" alt="Image for {{ book.title }}">
    {% else %}
        <p>No image for {{ book.title }}</p>
    {% endif %}
</div>

<div>
    {% comment %} <a href="{% url 'library:update_book_model_form' book.id %}">Update Book</a> {% endcomment %}
    <a href="{% url 'library:update_book_manual_form' book.id %}">Update Book</a>
    <a href="{% url 'library:confirm_delete' book.id %}">Delete Book</a>
</div>

{% endblock body %}

lms/templates/library/book-list.html
{% extends "partials/base.html" %}

{% block title %}
Book List
{% endblock title %}


{% block body %}
<h1>List of Books</h1>
<div>
    {% for book in all_books %}
        <h3><a href="{% url 'library:book_detail' book.pk %}">{{ book.title }}</a></h3>
        <h4>By {{ book.author }}</h4>
        <p>Number of Pages: {{ book.number_of_pages }}</p>
        <p>Published On: {{ book.published_on }}</p>
        {% if book.cover_image %}
            <img width="100" height="100" src="{{ book.cover_image.url }}" alt="Image for {{ book.title }}">
        {% else %}
            <p>No image for {{ book.title }}</p>
        {% endif %}
    {% endfor %}
</div>
{% endblock body %}

lms/templates/library/confirm-delete.html
{% extends "partials/base.html" %}

{% block title %}
Confirm Delete
{% endblock title %}


{% block body %}
<h1>Are you sure you want to delete {{ book.title }}?</h1>
<div>
    <form action="{% url 'library:delete_book' book.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">Yes, I am sure</button>
    </form>
    <a href="{% url 'library:book_detail' book.pk %}">No, take me back</a>
</div>
{% endblock body %}

lms/templates/library/create-book-django-manual-form.html
{% extends "partials/base.html" %}

{% block title %}
Add a Book
{% endblock title %}


{% block body %}
<h1>Add Book</h1>
<form action="{% url 'library:create_book_django_manual_form' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
    {{ form.as_p }}
    </div>
    
    <button type="submit">Add Book</button>
</form>
{% endblock body %}

{% comment %} django crsipy forms {% endcomment %}

lms/templates/library/create-book-manually-rendered.html
{% extends "partials/base.html" %}

{% block title %}
Add a Book
{% endblock title %}


{% block body %}
<h1>Add Book</h1>
<form action="{% url 'library:create_book_manually_rendered' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div>

        <ul>
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>

        <div>
            <ul>
                {% for error in form.title.errors %}
                    <li>{{ error }}</li>            
                {% endfor %}
            </ul>
            <label for="title">Title:</label>
            <input type="text" name="title" value="{{ form.title.value|default:'' }}" required>
        </div>
        <div>
            <ul>
                {% for error in form.author.errors %}
                    <li>{{ error }}</li>            
                {% endfor %}
            </ul>
            <label for="author">Author:</label>


            <select name="author">
                <option value="" selected="">---------</option>
                {% comment %} {% for author in all_authors %} {% endcomment %}
                {% for author in form.fields.author.queryset %}
                    <option value="{{ author.id }}" {% if form.author.value|stringformat:"s" == author.id|stringformat:"s" %}selected{% endif %}>{{ author.first_name }} {{ author.last_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <ul>
                {% for error in form.number_of_pages.errors %}
                    <li>{{ error }}</li>            
                {% endfor %}
            </ul>
            <label for="number_of_pages">Number of pages:</label>
            <input type="number" name="number_of_pages" value="{{ form.number_of_pages.value|default:'' }}" min="{{ form.fields.number_of_pages.min_value }}" required>
        </div>
        <div>
            <ul>
                {% for error in form.published_on.errors %}
                    <li>{{ error }}</li>            
                {% endfor %}
            </ul>
            <label for="published_on">Published on:</label>
            <input type="date" name="published_on" value="{{ form.published_on.value|default:'' }}" required>
        </div>
        <div>
            <ul>
                {% for error in form.cover_image.errors %}
                    <li>{{ error }}</li>            
                {% endfor %}
            </ul>
            <label for="cover_image">Cover image:</label>
            <input type="file" accept="image/*" name="cover_image">
        </div>
    </div>
    <button type="submit">Add Book</button>
</form>
{% endblock body %}

{% comment %} django crsipy forms {% endcomment %}

lms/templates/library/create-book.html
{% extends "partials/base.html" %}

{% block title %}
Add a Book
{% endblock title %}


{% block body %}
<h1>Add Book</h1>
<form action="{% url 'library:create_book' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
    </div>
    <button type="submit">Add Book</button>
</form>
{% endblock body %}

{% comment %} django crsipy forms {% endcomment %}

lms/templates/library/home.html
{% extends "partials/base.html" %}

{% block title %}
Home
{% endblock title %}


{% block body %}
<h1>Library landing page</h1>
{% endblock body %}

lms/templates/library/update-book-django-manual-form.html
{% extends "partials/base.html" %}

{% block title %}
Update {{ book.title }}
{% endblock title %}


{% block body %}
<h1>Update {{ book.title }}</h1>
<form action="{% url 'library:update_book_manual_form' book.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
    {{ form.as_p }}
    </div>
    
    <button type="submit">Update Book</button>
</form>
{% endblock body %}

{% comment %} django crsipy forms {% endcomment %}

lms/templates/library/update-book-model-form.html
{% extends "partials/base.html" %}

{% block title %}
Add a Book
{% endblock title %}


{% block body %}
<h1>Update Book</h1>
<form action="{% url 'library:update_book_model_form' book.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
    </div>
    <button type="submit">Update Book</button>
</form>
{% endblock body %}

{% comment %} django crsipy forms {% endcomment %}