lms/authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('', views.all_authors, name='all_authors'),
    path('book-signings/', views.book_signings, name='book_signings'),
    path('author/<str:author_pk>/', views.author_detail, name='author_detail'),
    path('add/author/', views.create_author, name='create_author'),
]

lms/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('authors/', include('authors.urls')), 
    path('dtl/', include('dtl.urls')), 
    path('', include('pages.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lms/dtl/urls.py
from django.urls import path

from . import views

app_name = 'dtl'

urlpatterns = [
    path('demo/', views.django_template_language, name='dtl_demo'),
    path('home/', views.home, name='home'),
    path('models-demo/', views.models_demo, name='models_demo'),
]

lms/authors/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    # id = models.UUIDField(primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField()
    image = models.ImageField(upload_to="author_images/", default="defaults/default_author.jpg")

    # class Meta:
    #     table_name = "authors"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

 

lms/authors/forms.py
from django import forms

from .models import Author

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'birth_date', 'image']

lms/authors/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Author
from .forms import AuthorForm

# Create your views here.

def all_authors(request):
    return render(request, "authors/all-authors.html", {"all_authors": Author.objects.all()})

def book_signings(request):
    return render(request, "authors/book-signings.html")


def author_detail(request, author_pk):
    author = get_object_or_404(Author, pk=author_pk)
    return render(request, "authors/author-detail.html", {"author": author})


def create_author(request):
    form = AuthorForm()
    if request.method == "POST":
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('authors:all_authors')
    return render(request, "authors/add-author.html", {'form': form})

lms/templates/authors/add-author.html
{% extends "partials/base.html" %}

{% block title %}Add Author{% endblock title %}

{% block body %}
<h1>Add Author</h1>

<div>
    <form action="{% url 'authors:create_author' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Author</button>
    </form>    
</div>

{% comment %} csrf - cross-site request forgery attack {% endcomment %}
{% endblock body %}

lms/templates/authors/all-authors.html
{% extends "partials/base.html" %}

{% block title %}All Authors{% endblock title %}

{% block body %}
<h1>List of Authors</h1>

<div>
{% csrf_token %}
    {% for author in all_authors %}
        <h3><a href="{% url 'authors:author_detail' author.id %}">{{ author.first_name }} {{ author.last_name }}</a></h3>
        <p>Born on {{ author.birth_date }}</p>
        <img width="100" height="100" src="{{ author.image.url }}" alt="Image of {{ author }}">
    {% endfor %}
</div>

{% comment %} csrf - cross-site request forgery attack {% endcomment %}
{% endblock body %}

lms/templates/authors/author-detail.html
{% extends "partials/base.html" %}

{% block title %}{{ author.first_name }} {{ author.last_name }}{% endblock title %}

{% block body %}
<h1>{{ author.first_name }} {{ author.last_name }}</h1>

<div>
    <h3>{{ author.first_name }} {{ author.last_name }}</h3>
    <p>Born on {{ author.birth_date }}</p>
    <img width="100" height="100" src="{{ author.image.url }}" alt="Image of {{ author }}">
</div>
{% endblock body %}

lms/templates/authors/book-signings.html
{% extends "partials/base.html" %}

{% block title %}
Upcoming Book Signings
{% endblock title %}


{% block body %}
<h1>Upcoming Book Signings</h1>
{% endblock body %}